# Generated by Django 5.0.4 on 2024-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_comments',
            field=models.ManyToManyField(related_name='bookmarking_users', to='news.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_stories',
            field=models.ManyToManyField(related_name='bookmarking_users', to='news.story'),
        ),
    ]
